## Learning Objectives

In this tutorial, you will practice:

-   using LLMs via chat interface to generate datasets
-   evaluating LLM generated data in R

Feel free to chat with an LLM as part of these exercises.

## Exercise 1

Haley has encountered some missing data in the age column of her wild caught census data, and she tries using ChatGPT to fix the issue:

- [Chat 1](https://chatgpt.com/share/6828c268-85e0-8000-91ef-ceb73ed32d6c)
- [Chat 2](https://chatgpt.com/share/6828c2ee-a3b0-8000-a956-692974053b43)

Examine the two chats:

- do they return the same data?
- which answer seems more reliable?
- is any important information missing from the chat?
- would you recommend that Haley use the LLM generated data in an analysis of trends in the average age of different suburbs?
- does your recommendation depend on the type of analysis?

## Exercise 2

Recall the data preparation tasks discussed in lecture

- **looking up missing information**
- **suggesting values**
- **harmonise different abbreviations**
- **comparing and categorising**
- **summarising text**
- **extracting information**

Imagine you are working on a data analysis project where all of these tasks are required to prepare the analysis dataset. 

Discuss in groups:

- Which of these tasks would you feel most confident using an LLM to complete? Why?
- Which of these tasks would you prefer to have a human complete? Why?
- Which of these tasks would be most difficult to verify the correctness of?
- How would your answers change depending on the type of dataset you are working with?

## Exercise 3

Import and examine the nationality columns in the author dataset `week11-author_df_llm.csv` in R.

Subset the list of authors into groups based on how confidently you could answer what the author's nationality is. 
[Hint: Consider creating a new column comparing the LLM nationalities with the web-scraped nationalities]


#### Copyright Monash University